### ISSUE TITLE
Bug in the icons with name

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#75]
@baimingze the icons are showing the name of the omics see the example. Close to the genomics icon I have the word genomics. Have you tested this... please do not commit code that is not working or breaking things. 

<img width="802" alt="screen shot 2016-06-15 at 17 52 30" src="https://cloud.githubusercontent.com/assets/52113/16089247/26693fee-3322-11e6-8445-3abad86fc372.png">

**Comment by baimingze** [comment]
I can't remember when this Word has been added in, and by who. Do you want me to remove this?

**Comment by ypriverol** [comment]
@baimingze here the console in the search page .. couple of errors:


4angular.js:12138 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:212:409), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at h (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:87:376)
    at K (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:91:499)
    at XMLHttpRequest.z.onload (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:93:37)(anonymous function) @ angular.js:12138
angular.js:12138 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:212:409), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:146:300
    at e (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:43:95)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:45:491(anonymous function) @ angular.js:12138
2angular.min.js:107 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:212:409), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/autocomplete.js:159:17(anonymous function) @ angular.min.js:107
angular.min.js:107 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:212:409), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:146:300
    at e (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:43:95)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:45:491(anonymous function) @ angular.min.js:107
2angular.min.js:107 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:212:409), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at updateCount (http://localhost:8000/Tools/omicsdi/bower_components/angular/ngprogress.min.js:8:1128)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/ngprogress.min.js:8:2400
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:146:222
    at e (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:43:95)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:45:491(anonymous function) @ angular.min.js:107
3angular.min.js:107 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:212:409), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:146:300
    at e (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:43:95)
    at http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:45:491(anonymous function) @ angular.min.js:107
http://localhost:9091/dataset/mostAccessed?size=20 Failed to load resource: the server responded with a status of 500 (Timed out after 30000 ms while waiting for a server that matches {serverSelectors=[MongosHAServerSelector{}, LatencyMinimizingServerSelector{acceptableLatencyDifference=15 ms}]}. Client view of cluster state is {type=Sharded, servers=[{address=mongos-hxvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-hxvm-001.ebi.ac.uk: unknown error}}, {address=mongos-oyvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-oyvm-001.ebi.ac.uk: unknown error}}, {address=mongos-pgvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-pgvm-001.ebi.ac.uk: unknown error}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches {serverSelectors=[MongosHAServerSelector{}, LatencyMinimizingServerSelector{acceptableLatencyDifference=15 ms}]}. Client view of cluster state is {type=Sharded, servers=[{address=mongos-hxvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-hxvm-001.ebi.ac.uk: unknown error}}, {address=mongos-oyvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-oyvm-001.ebi.ac.uk: unknown error}}, {address=mongos-pgvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-pgvm-001.ebi.ac.uk: unknown error}}])
DDIDatasetListsCtl.js:59 GET error:http://localhost:9091/statistics/domains
angular.min.js:107 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:212:409), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at h (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:87:376)
    at K (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:91:499)
    at XMLHttpRequest.z.onload (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:93:37)(anonymous function) @ angular.min.js:107
http://localhost:9091/dataset/mostAccessed?size=20 Failed to load resource: the server responded with a status of 500 (Timed out after 30000 ms while waiting for a server that matches {serverSelectors=[MongosHAServerSelector{}, LatencyMinimizingServerSelector{acceptableLatencyDifference=15 ms}]}. Client view of cluster state is {type=Sharded, servers=[{address=mongos-hxvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-hxvm-001.ebi.ac.uk: unknown error}}, {address=mongos-oyvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-oyvm-001.ebi.ac.uk: unknown error}}, {address=mongos-pgvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-pgvm-001.ebi.ac.uk: unknown error}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches {serverSelectors=[MongosHAServerSelector{}, LatencyMinimizingServerSelector{acceptableLatencyDifference=15 ms}]}. Client view of cluster state is {type=Sharded, servers=[{address=mongos-hxvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-hxvm-001.ebi.ac.uk: unknown error}}, {address=mongos-oyvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-oyvm-001.ebi.ac.uk: unknown error}}, {address=mongos-pgvm-001.ebi.ac.uk:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: mongos-pgvm-001.ebi.ac.uk: unknown error}}])
DDIDatasetListsCtl.js:59 GET error:http://localhost:9091/statistics/domains
angular.min.js:107 SyntaxError: Invalid regular expression: /modification\:"propanoyl labeling reagent heavy form (+3amu) (K)"/: Nothing to repeat
    at RegExp (native)
    at n.$scope.is_facet_applied (http://localhost:8000/Tools/omicsdi/js/DDIResultsListCtl.js:180:27)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:1:0), <anonymous>:4:865)
    at n.$digest (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:130:348)
    at n.$apply (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:133:512)
    at h (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:87:376)
    at K (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:91:499)
    at XMLHttpRequest.z.onload (http://localhost:8000/Tools/omicsdi/bower_components/angular/angular.min.js:93:37)(anonymous function) @ angular.min.js:107

**Comment by ypriverol** [comment]
Issue Solve.
